# CMake generated Testfile for 
# Source directory: C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests
# Build directory: C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_config "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_config.exe")
  set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;10;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_config "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_config.exe")
  set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;10;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_config "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_config.exe")
  set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;10;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_config "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_config.exe")
  set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;10;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_config NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_gsm_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_gsm_phy.exe")
  set_tests_properties(test_gsm_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;15;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_gsm_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_gsm_phy.exe")
  set_tests_properties(test_gsm_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;15;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_gsm_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_gsm_phy.exe")
  set_tests_properties(test_gsm_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;15;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_gsm_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_gsm_phy.exe")
  set_tests_properties(test_gsm_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;15;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_gsm_phy NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_lte_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_lte_mac.exe")
  set_tests_properties(test_lte_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;20;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_lte_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_lte_mac.exe")
  set_tests_properties(test_lte_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;20;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_lte_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_lte_mac.exe")
  set_tests_properties(test_lte_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;20;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_lte_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_lte_mac.exe")
  set_tests_properties(test_lte_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;20;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_lte_mac NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_pdcp "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_pdcp.exe")
  set_tests_properties(test_pdcp PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;25;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_pdcp "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_pdcp.exe")
  set_tests_properties(test_pdcp PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;25;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_pdcp "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_pdcp.exe")
  set_tests_properties(test_pdcp PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;25;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_pdcp "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_pdcp.exe")
  set_tests_properties(test_pdcp PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;25;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_pdcp NOT_AVAILABLE)
endif()
