# CMake generated Testfile for 
# Source directory: C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests
# Build directory: C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_config "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_config.exe")
  set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;10;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_config "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_config.exe")
  set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;10;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_config "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_config.exe")
  set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;10;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_config "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_config.exe")
  set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;10;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_config NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_gsm_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_gsm_phy.exe")
  set_tests_properties(test_gsm_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;15;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_gsm_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_gsm_phy.exe")
  set_tests_properties(test_gsm_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;15;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_gsm_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_gsm_phy.exe")
  set_tests_properties(test_gsm_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;15;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_gsm_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_gsm_phy.exe")
  set_tests_properties(test_gsm_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;15;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_gsm_phy NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_lte_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_lte_mac.exe")
  set_tests_properties(test_lte_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;20;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_lte_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_lte_mac.exe")
  set_tests_properties(test_lte_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;20;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_lte_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_lte_mac.exe")
  set_tests_properties(test_lte_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;20;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_lte_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_lte_mac.exe")
  set_tests_properties(test_lte_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;20;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_lte_mac NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_pdcp "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_pdcp.exe")
  set_tests_properties(test_pdcp PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;25;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_pdcp "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_pdcp.exe")
  set_tests_properties(test_pdcp PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;25;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_pdcp "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_pdcp.exe")
  set_tests_properties(test_pdcp PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;25;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_pdcp "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_pdcp.exe")
  set_tests_properties(test_pdcp PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;25;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_pdcp NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_lte_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_lte_phy.exe")
  set_tests_properties(test_lte_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;30;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_lte_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_lte_phy.exe")
  set_tests_properties(test_lte_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;30;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_lte_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_lte_phy.exe")
  set_tests_properties(test_lte_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;30;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_lte_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_lte_phy.exe")
  set_tests_properties(test_lte_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;30;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_lte_phy NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_lte_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_lte_rlc.exe")
  set_tests_properties(test_lte_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;35;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_lte_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_lte_rlc.exe")
  set_tests_properties(test_lte_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;35;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_lte_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_lte_rlc.exe")
  set_tests_properties(test_lte_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;35;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_lte_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_lte_rlc.exe")
  set_tests_properties(test_lte_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;35;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_lte_rlc NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_umts_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_umts_mac.exe")
  set_tests_properties(test_umts_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;40;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_umts_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_umts_mac.exe")
  set_tests_properties(test_umts_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;40;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_umts_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_umts_mac.exe")
  set_tests_properties(test_umts_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;40;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_umts_mac "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_umts_mac.exe")
  set_tests_properties(test_umts_mac PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;40;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_umts_mac NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_s1ap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_s1ap_codec.exe")
  set_tests_properties(test_s1ap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;45;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_s1ap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_s1ap_codec.exe")
  set_tests_properties(test_s1ap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;45;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_s1ap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_s1ap_codec.exe")
  set_tests_properties(test_s1ap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;45;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_s1ap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_s1ap_codec.exe")
  set_tests_properties(test_s1ap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;45;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_s1ap_codec NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_x2ap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_x2ap_codec.exe")
  set_tests_properties(test_x2ap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;50;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_x2ap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_x2ap_codec.exe")
  set_tests_properties(test_x2ap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;50;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_x2ap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_x2ap_codec.exe")
  set_tests_properties(test_x2ap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;50;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_x2ap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_x2ap_codec.exe")
  set_tests_properties(test_x2ap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;50;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_x2ap_codec NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_nbap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_nbap_codec.exe")
  set_tests_properties(test_nbap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;55;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_nbap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_nbap_codec.exe")
  set_tests_properties(test_nbap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;55;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_nbap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_nbap_codec.exe")
  set_tests_properties(test_nbap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;55;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_nbap_codec "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_nbap_codec.exe")
  set_tests_properties(test_nbap_codec PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;55;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_nbap_codec NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_gtp_u "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_gtp_u.exe")
  set_tests_properties(test_gtp_u PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;60;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_gtp_u "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_gtp_u.exe")
  set_tests_properties(test_gtp_u PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;60;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_gtp_u "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_gtp_u.exe")
  set_tests_properties(test_gtp_u PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;60;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_gtp_u "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_gtp_u.exe")
  set_tests_properties(test_gtp_u PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;60;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_gtp_u NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_lte_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_lte_stack.exe")
  set_tests_properties(test_lte_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;65;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_lte_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_lte_stack.exe")
  set_tests_properties(test_lte_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;65;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_lte_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_lte_stack.exe")
  set_tests_properties(test_lte_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;65;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_lte_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_lte_stack.exe")
  set_tests_properties(test_lte_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;65;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_lte_stack NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_gsm_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_gsm_stack.exe")
  set_tests_properties(test_gsm_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;70;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_gsm_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_gsm_stack.exe")
  set_tests_properties(test_gsm_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;70;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_gsm_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_gsm_stack.exe")
  set_tests_properties(test_gsm_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;70;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_gsm_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_gsm_stack.exe")
  set_tests_properties(test_gsm_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;70;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_gsm_stack NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_umts_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_umts_stack.exe")
  set_tests_properties(test_umts_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;75;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_umts_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_umts_stack.exe")
  set_tests_properties(test_umts_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;75;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_umts_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_umts_stack.exe")
  set_tests_properties(test_umts_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;75;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_umts_stack "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_umts_stack.exe")
  set_tests_properties(test_umts_stack PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;75;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_umts_stack NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_oms "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_oms.exe")
  set_tests_properties(test_oms PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;80;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_oms "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_oms.exe")
  set_tests_properties(test_oms PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;80;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_oms "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_oms.exe")
  set_tests_properties(test_oms PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;80;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_oms "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_oms.exe")
  set_tests_properties(test_oms PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;80;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_oms NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_gsm_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_gsm_rlc.exe")
  set_tests_properties(test_gsm_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;85;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_gsm_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_gsm_rlc.exe")
  set_tests_properties(test_gsm_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;85;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_gsm_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_gsm_rlc.exe")
  set_tests_properties(test_gsm_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;85;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_gsm_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_gsm_rlc.exe")
  set_tests_properties(test_gsm_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;85;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_gsm_rlc NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_gsm_rr "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_gsm_rr.exe")
  set_tests_properties(test_gsm_rr PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;90;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_gsm_rr "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_gsm_rr.exe")
  set_tests_properties(test_gsm_rr PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;90;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_gsm_rr "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_gsm_rr.exe")
  set_tests_properties(test_gsm_rr PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;90;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_gsm_rr "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_gsm_rr.exe")
  set_tests_properties(test_gsm_rr PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;90;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_gsm_rr NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_umts_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_umts_phy.exe")
  set_tests_properties(test_umts_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;95;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_umts_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_umts_phy.exe")
  set_tests_properties(test_umts_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;95;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_umts_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_umts_phy.exe")
  set_tests_properties(test_umts_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;95;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_umts_phy "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_umts_phy.exe")
  set_tests_properties(test_umts_phy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;95;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_umts_phy NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_umts_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_umts_rlc.exe")
  set_tests_properties(test_umts_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;100;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_umts_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_umts_rlc.exe")
  set_tests_properties(test_umts_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;100;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_umts_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_umts_rlc.exe")
  set_tests_properties(test_umts_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;100;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_umts_rlc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_umts_rlc.exe")
  set_tests_properties(test_umts_rlc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;100;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_umts_rlc NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_umts_rrc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_umts_rrc.exe")
  set_tests_properties(test_umts_rrc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;105;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_umts_rrc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_umts_rrc.exe")
  set_tests_properties(test_umts_rrc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;105;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_umts_rrc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_umts_rrc.exe")
  set_tests_properties(test_umts_rrc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;105;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_umts_rrc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_umts_rrc.exe")
  set_tests_properties(test_umts_rrc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;105;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_umts_rrc NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_lte_rrc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_lte_rrc.exe")
  set_tests_properties(test_lte_rrc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;110;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_lte_rrc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_lte_rrc.exe")
  set_tests_properties(test_lte_rrc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;110;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_lte_rrc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_lte_rrc.exe")
  set_tests_properties(test_lte_rrc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;110;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_lte_rrc "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_lte_rrc.exe")
  set_tests_properties(test_lte_rrc PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;110;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_lte_rrc NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_s1ap_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_s1ap_link.exe")
  set_tests_properties(test_s1ap_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;115;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_s1ap_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_s1ap_link.exe")
  set_tests_properties(test_s1ap_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;115;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_s1ap_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_s1ap_link.exe")
  set_tests_properties(test_s1ap_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;115;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_s1ap_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_s1ap_link.exe")
  set_tests_properties(test_s1ap_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;115;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_s1ap_link NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_x2ap_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_x2ap_link.exe")
  set_tests_properties(test_x2ap_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;120;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_x2ap_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_x2ap_link.exe")
  set_tests_properties(test_x2ap_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;120;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_x2ap_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_x2ap_link.exe")
  set_tests_properties(test_x2ap_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;120;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_x2ap_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_x2ap_link.exe")
  set_tests_properties(test_x2ap_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;120;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_x2ap_link NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_abis_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_abis_link.exe")
  set_tests_properties(test_abis_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;125;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_abis_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_abis_link.exe")
  set_tests_properties(test_abis_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;125;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_abis_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_abis_link.exe")
  set_tests_properties(test_abis_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;125;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_abis_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_abis_link.exe")
  set_tests_properties(test_abis_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;125;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_abis_link NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_iub_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_iub_link.exe")
  set_tests_properties(test_iub_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;130;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_iub_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_iub_link.exe")
  set_tests_properties(test_iub_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;130;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_iub_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_iub_link.exe")
  set_tests_properties(test_iub_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;130;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_iub_link "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_iub_link.exe")
  set_tests_properties(test_iub_link PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;130;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_iub_link NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_integration "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_integration.exe")
  set_tests_properties(test_integration PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;135;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_integration "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_integration.exe")
  set_tests_properties(test_integration PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;135;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_integration "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_integration.exe")
  set_tests_properties(test_integration PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;135;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_integration "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_integration.exe")
  set_tests_properties(test_integration PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;135;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_integration NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_mobility "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_mobility.exe")
  set_tests_properties(test_mobility PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;140;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_mobility "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_mobility.exe")
  set_tests_properties(test_mobility PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;140;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_mobility "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_mobility.exe")
  set_tests_properties(test_mobility PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;140;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_mobility "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_mobility.exe")
  set_tests_properties(test_mobility PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;140;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_mobility NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_son "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Debug/test_son.exe")
  set_tests_properties(test_son PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;145;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_son "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/Release/test_son.exe")
  set_tests_properties(test_son PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;145;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_son "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/MinSizeRel/test_son.exe")
  set_tests_properties(test_son PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;145;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_son "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/build-asn1/tests/RelWithDebInfo/test_son.exe")
  set_tests_properties(test_son PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;145;add_test;C:/Users/Alexey/Desktop/min/vNE/RBS/RBS/tests/CMakeLists.txt;0;")
else()
  add_test(test_son NOT_AVAILABLE)
endif()
